"""Initial migrate

Revision ID: 12271f6bae80
Revises: 
Create Date: 2026-01-24 00:26:20.291249

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12271f6bae80'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=2), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_countries_code'), ['code'], unique=True)

    op.create_table('course_categories',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_categories', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_categories_code'), ['code'], unique=True)

    op.create_table('languages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('code', sa.String(length=10), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('is_default', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_table('subscription_plans',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='BASIC, SMART, PRO'),
    sa.Column('duration_months', sa.Integer(), nullable=False, comment='3, 6, 12'),
    sa.Column('price', sa.Float(), nullable=False, comment='195000, 300000, 516000'),
    sa.Column('visits_limit', sa.Integer(), nullable=False, comment='20, 30, 40'),
    sa.Column('description', sa.Text(), nullable=True, comment='Для знакомства с форматом'),
    sa.Column('is_active', sa.Boolean(), server_default='true', nullable=False),
    sa.Column('display_order', sa.Integer(), nullable=False, comment='Порядок отображения'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('telegram_id', sa.BigInteger(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=True),
    sa.Column('first_name', sa.String(length=64), nullable=True),
    sa.Column('last_name', sa.String(length=64), nullable=True),
    sa.Column('phone', sa.String(length=32), nullable=True),
    sa.Column('role', sa.Enum('ADMIN', 'USER', 'PARENT', 'CHILD', 'PARTNER', name='role', native_enum=False), server_default='USER', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_role'), ['role'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_telegram_id'), ['telegram_id'], unique=True)

    op.create_table('cities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cities_country_id'), ['country_id'], unique=False)

    op.create_table('country_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country_id', 'language_id', name='uq_country_language')
    )
    with op.batch_alter_table('country_translations', schema=None) as batch_op:
        batch_op.create_index('idx_country_lang', ['country_id', 'language_id'], unique=False)

    op.create_table('course_category_translations',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=128), nullable=False),
    sa.ForeignKeyConstraint(['category_id'], ['course_categories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('course_category_translations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_category_translations_category_id'), ['category_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_course_category_translations_language_id'), ['language_id'], unique=False)

    op.create_table('city_translations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city_id', sa.Integer(), nullable=False),
    sa.Column('language_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.ForeignKeyConstraint(['city_id'], ['cities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['language_id'], ['languages.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('city_id', 'language_id', name='uq_city_language')
    )
    with op.batch_alter_table('city_translations', schema=None) as batch_op:
        batch_op.create_index('idx_city_lang', ['city_id', 'language_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_city_translations_name'), ['name'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('city_translations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_city_translations_name'))
        batch_op.drop_index('idx_city_lang')

    op.drop_table('city_translations')
    with op.batch_alter_table('course_category_translations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_category_translations_language_id'))
        batch_op.drop_index(batch_op.f('ix_course_category_translations_category_id'))

    op.drop_table('course_category_translations')
    with op.batch_alter_table('country_translations', schema=None) as batch_op:
        batch_op.drop_index('idx_country_lang')

    op.drop_table('country_translations')
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cities_country_id'))

    op.drop_table('cities')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_telegram_id'))
        batch_op.drop_index(batch_op.f('ix_users_role'))
        batch_op.drop_index(batch_op.f('ix_users_is_deleted'))

    op.drop_table('users')
    op.drop_table('subscription_plans')
    op.drop_table('languages')
    with op.batch_alter_table('course_categories', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_categories_code'))

    op.drop_table('course_categories')
    with op.batch_alter_table('countries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_countries_code'))

    op.drop_table('countries')
    # ### end Alembic commands ###