"""add subscription table and payment table

Revision ID: 7810017f2bed
Revises: cf81387f26f3
Create Date: 2026-01-24 01:24:56.950643

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7810017f2bed'
down_revision: Union[str, Sequence[str], None] = 'cf81387f26f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False, comment='Payment amount in cents'),
    sa.Column('currency', sa.String(length=8), server_default='KZT', nullable=False),
    sa.Column('status', sa.Enum('NEW', 'SECURE_3D', 'AUTH', 'SUCCESS', 'ERROR', 'RETURN', 'REFUND', 'UNBLOCK', name='paymentstatus', native_enum=False), server_default='new', nullable=False),
    sa.Column('payment_id', sa.String(length=128), nullable=True, comment='External payment gateway payment ID'),
    sa.Column('invoice_id', sa.String(length=128), nullable=True, comment='Invoice ID from payment gateway'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_payments_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_payments'))
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_payment_id'), ['payment_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_user_id'), ['user_id'], unique=False)

    op.create_table('subscriptions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('subscription_plan_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'EXPIRED', 'CANCELLED', name='subscriptionstatus', native_enum=False), server_default='ACTIVE', nullable=False),
    sa.Column('starts_at', sa.DateTime(), nullable=False, comment='Subscription start date'),
    sa.Column('expires_at', sa.DateTime(), nullable=False, comment='Subscription expiration date'),
    sa.Column('payment_id', sa.Integer(), nullable=True, comment='Associated payment'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], name=op.f('fk_subscriptions_payment_id_payments'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['subscription_plan_id'], ['subscription_plans.id'], name=op.f('fk_subscriptions_subscription_plan_id_subscription_plans'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_subscriptions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_subscriptions'))
    )
    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_subscriptions_expires_at'), ['expires_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_subscription_plan_id'), ['subscription_plan_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_subscriptions_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('languages_code_key'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_languages_code'), ['code'])

    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('subscription_plans_name_key'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('uq_subscription_plans_name'), ['name'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subscription_plans', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_subscription_plans_name'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('subscription_plans_name_key'), ['name'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('languages', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_languages_code'), type_='unique')
        batch_op.create_unique_constraint(batch_op.f('languages_code_key'), ['code'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('subscriptions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_subscriptions_user_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_subscription_plan_id'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_status'))
        batch_op.drop_index(batch_op.f('ix_subscriptions_expires_at'))

    op.drop_table('subscriptions')
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_user_id'))
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_index(batch_op.f('ix_payments_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payments_invoice_id'))

    op.drop_table('payments')
    # ### end Alembic commands ###